#!/bin/bash
#conda activate astro_Python_ubuntu_env
#cd /mnt/Rdata/CCD_obs/astro_Python
python 01_1_modify_fits_header_listall.py
#python 01_2_move_fit_file_to_one_folder_for_wcs_listall.py
#python 01_3_move_fit_file_to_one_folder_for_wcs_listall.py
python 01_4_rename_wcs_fits_files_with_optic_keyword_listall.py
